### ISSUE TITLE
Can't get brightness above 24 %

### ISSUE THREAD

**Issue by Synasenn** [lkempf/casambi-bt-hass#22]
First; love this integration! works so much better than the integration through the gateway and android app!

Second; I am facing a small issue, that I cannot get the lights to go brighter than 24, which reklates to 23.9% in casambi app.
As soon as I try to go higher through homeassistant I get a "ValueError: byte must be in range(0, 256)" error.

Small issue for me, since I hardly ever want it brighter anyway, but still wondering why it's happening.

Logs: tried to set brightness to 25
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/casambi_bt/light.py:209
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:52:01 (1 occurrences)
Last logged: 11:52:01

[547710476608] byte must be in range(0, 256)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 681, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 721, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 571, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/casambi_bt/light.py", line 209, in async_turn_on
    await self._api.casa.setUnitState(self._obj, state)
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_casambi.py", line 150, in setUnitState
    stateBytes = target.getStateAsBytes(state)
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_unit.py", line 265, in getStateAsBytes
    res[off // 8] |= valBytes[i] << (off % 8)
ValueError: byte must be in range(0, 256)
```

**Comment by mintnl** [comment]
Same issue as https://github.com/lkempf/casambi-bt/issues/9 
What kind of dimmer do you happen to use? In my case this is happening with the trailing edge dimmer.

**Comment by Synasenn** [comment]
sorry, did not mean to raise a double issue.

I have a few CBU-TED's, I think that's the trailing edge dimmer you mean as well

**Comment by mintnl** [comment]
Should be fixed in latest RC
