### ISSUE TITLE
Unexpected answer from device! Wrong device or protocol version?

### ISSUE THREAD

**Issue by RolfDeL** [lkempf/casambi-bt-hass#24]
Hi, 
I'm trying to get this working, but get this unexpected Error when trying to connect.
It's a Classic (Not evolution) network with firmware v26.24

Logs:

his error originated from a custom integration.

Logger: custom_components.casambi_bt.config_flow
Source: custom_components/casambi_bt/config_flow.py:41
Integration: Casambi Bluetooth (documentation)
First occurred: 22:47:51 (1 occurrences)
Last logged: 22:47:51

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/casambi_bt/config_flow.py", line 122, in async_step_user
    info = await _validate_input(self.hass, user_input)
  File "/config/custom_components/casambi_bt/config_flow.py", line 41, in _validate_input
    await casa.connect(bt_device, data[CONF_PASSWORD])
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_casambi.py", line 126, in connect
    await self._connectClient()
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_casambi.py", line 141, in _connectClient
    raise e
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_casambi.py", line 137, in _connectClient
    await self._casaClient.exchangeKey(self._casaNetwork.getKeyStore())
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_client.py", line 142, in exchangeKey
    raise ProtocolError(
CasambiBt.errors.ProtocolError: Unexpected answer from device! Wrong device or protocol version?

Thanks for your help
Rolf

**Comment by lkempf** [comment]
Classic isn't currently supported (see #6). I'm slowly trying to understand the protocol but it's a lot of work.

**Comment by RolfDeL** [comment]
OK, no problem. Thanks for your reply.
You can close the issue then. i will watch the repository for updates.
