### ISSUE TITLE
v0.0.6-rc1 'CasambiClient' object has no attribute '_callbackTask'

### ISSUE THREAD

**Issue by tjorim** [lkempf/casambi-bt-hass#26]
I'm on the beta release (v0.0.6-rc1) and see this error:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/casambi_bt/__init__.py:170
Integration: Casambi Bluetooth (documentation)
First occurred: 12:55:56 AM (829 occurrences)
Last logged: 8:11:37 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/casambi_bt/__init__.py", line 170, in try_reconnect
    await self.casa.disconnect()
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_casambi.py", line 360, in disconnect
    await self._casaClient.disconnect()
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_client.py", line 459, in disconnect
    if self._callbackTask:
AttributeError: 'CasambiClient' object has no attribute '_callbackTask'
```

**Comment by lkempf** [comment]
Are you using multiple casambi networks in HA at the same time? If so I have a theory on why this is happening. Otherwise I can do a quick workaround for the next release.

**Comment by lkempf** [comment]
I hope I implemented a workaround for this issue. Please reopen if the issue persists.
