### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by tjorim** [lkempf/casambi-bt-hass#31]
**Describe the bug**
I removed the existing integration, installed version 0.0.6 and set it up once discovered. It creates the entities but does not work.

**Expected behavior**
No errors and a working light.

**Versions**
- HA version: 2023.4.1
## System Information

version | core-2023.4.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.19-v8
arch | aarch64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4998
Installed Version | 1.31.0
Stage | running
Available Repositories | 1252
Downloaded Repositories | 67
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0.rc3
-- | --
update_channel | beta
supervisor_version | supervisor-2023.04.0
agent_version | 1.5.1
docker_version | 23.0.2
disk_total | 458.4 GB
disk_used | 32.8 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | AirCast (3.5.2), Spotify Connect (0.12.3), SSH & Web Terminal (13.1.0), File editor (5.5.0), Studio Code Server (5.5.6), Zigbee2MQTT (1.30.3-1), Home Assistant Google Drive Backup (0.110.3), MariaDB (2.5.2), phpMyAdmin (0.8.5), JupyterLab (0.10.0), The Lounge (0.17.1), Glances (0.18.1), Tailscale (0.10.1), ZeroTier One (0.16.2), AdGuard Home (4.8.4), Nginx Proxy Manager (0.12.3), Uptime Kuma (0.7.2), WireGuard (0.8.0), CUPS Print Server (2.0.2), ESPHome (2023.3.2), Grafana (8.2.1), Music Assistant BETA (2.0.0b27), Mosquitto broker (6.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 28
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 11, 2022 at 07:18
-- | --
current_recorder_run | April 7, 2023 at 23:53
estimated_db_size | 7009.72 MiB
database_engine | mysql
database_version | 10.6.10

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>
- Integration version: 0.0.6

**Logs**
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/casambi_bt/__init__.py:179
Integration: Casambi Bluetooth (documentation)
First occurred: April 7, 2023 at 23:55:06 (1 occurrences)
Last logged: April 7, 2023 at 23:55:06

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 213, in connect_tcp
    async with create_task_group() as tg:
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 110, in connect_tcp
    with anyio.fail_after(timeout):
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/casambi_bt/__init__.py", line 179, in try_reconnect
    await self.casa.connect(device, self.password)
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_casambi.py", line 129, in connect
    await self._casaNetwork.logIn(password, forceOffline)
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_network.py", line 135, in logIn
    await self.getNetworkId(forceOffline)
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_network.py", line 99, in getNetworkId
    res = await self._httpClient.get(getNetworkIdUrl)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
```

**Comment by lkempf** [comment]
The workaround for this issue should work in 0.0.7. I still don't know what the underlying cause is but I'm tracking that in #20.
