### ISSUE TITLE
Not connecting to Casambi Network

### ISSUE THREAD

**Issue by caeculus** [lkempf/casambi-bt-hass#38]
**Describe the bug**
When trying to connect to a discovered network a non descriptive standard error is given. When looking into the logfile more information is shown (see below). 
Seems that no backend connections are available (using a dedicated bluetooth 5.0 dongle).

Thank you for the assistance!

**To Reproduce**

**Expected behavior**
I expected that the casammbi devices would be shown, in this case I limited the network to only 1 device Xitanium 20W/m from signify with firmware evolution 39.40.

**Screenshots**

**Versions**
- HA version: latest version  2023.09.2
- Integration version: 0.07

**Logs**
This error originated from a custom integration.

Logger: custom_components.casambi_bt.config_flow
Source: custom_components/casambi_bt/config_flow.py:41
Integration: casambi_bt (documentation)
First occurred: 9:58:27 PM (1 occurrences)
Last logged: 9:58:27 PM

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 350, in establish_connection
    await client.connect(
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 273, in connect
    wrapped_backend = self._async_get_best_available_backend_and_device(manager)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 375, in _async_get_best_available_backend_and_device
    raise BleakError(
bleak.exc.BleakError: No backend with an available connection slot that can reach address D8:50:5B:98:7F:CE was found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/CasambiBt/_client.py", line 119, in connect
    self._gattClient = await establish_connection(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 438, in establish_connection
    _raise_if_needed(name, device.address, exc)
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 319, in _raise_if_needed
    raise BleakOutOfConnectionSlotsError(
bleak_retry_connector.BleakOutOfConnectionSlotsError: Casambi Network - D8:50:5B:98:7F:CE: Failed to connect after 9 attempt(s): No backend with an available connection slot that can reach address D8:50:5B:98:7F:CE was found: The proxy/adapter is out of connection slots or the device is no longer reachable; Add additional proxies (https://esphome.github.io/bluetooth-proxies/) near this device

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/casambi_bt/config_flow.py", line 124, in async_step_user
    info = await _validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/casambi_bt/config_flow.py", line 41, in _validate_input
    await casa.connect(bt_device, data[CONF_PASSWORD])
  File "/usr/local/lib/python3.11/site-packages/CasambiBt/_casambi.py", line 139, in connect
    await self._connectClient()
  File "/usr/local/lib/python3.11/site-packages/CasambiBt/_casambi.py", line 144, in _connectClient
    await self._casaClient.connect()
  File "/usr/local/lib/python3.11/site-packages/CasambiBt/_client.py", line 128, in connect
    raise BluetoothError(e.args) from e
CasambiBt.errors.BluetoothError: ('Casambi Network - D8:50:5B:98:7F:CE: Failed to connect after 9 attempt(s): No backend with an available connection slot that can reach address D8:50:5B:98:7F:CE was found: The proxy/adapter is out of connection slots or the device is no longer reachable; Add additional proxies (https://esphome.github.io/bluetooth-proxies/) near this device',)

**Comment by lkempf** [comment]
I know these errors from #3. I'm quite sure that this isn't an issue with my library but with the HA bluetooth stack and I'd recommend you just get a bluetooth dongle if possible.
