### ISSUE TITLE
Detected blocking call to...

### ISSUE THREAD

**Issue by tjorim** [lkempf/casambi-bt-hass#86]
**Describe the bug**

- [ ] Detected blocking call to read_text with args
```
Detected blocking call to read_text with args (PosixPath('/config/.storage/casambi_bt/6d2ab263d8b0/networkid'),) inside the event loop by custom integration 'casambi_bt' at custom_components/casambi_bt/__init__.py, line 102: await self.casa.connect(device, self.password) (offender: /usr/local/lib/python3.12/site-packages/CasambiBt/_network.py, line 96: self._id = networkCacheFile.read_text()), please report it to the author of the 'casambi_bt' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#read_text Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 960, in _read_ready self._read_ready_cb() File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1017, in _read_ready__data_received self._protocol.data_received(data) File "/usr/local/lib/python3.12/site-packages/bleak_esphome/backend/scanner.py", line 41, in async_on_raw_advertisements self._async_on_advertisement( File "/usr/src/homeassistant/homeassistant/components/bluetooth/manager.py", line 114, in _discover_service_info discovery_flow.async_create_flow( File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 36, in async_create_flow hass.async_create_background_task( File "/usr/src/homeassistant/homeassistant/core.py", line 861, in async_create_background_task task = create_eager_task(target, name=name, loop=self.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1296, in async_init flow, result = await self._async_init(flow_id, handler, context, data) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1331, in _async_init result = await self._async_handle_step(flow, flow.init_step, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/casambi_bt/config_flow.py", line 116, in async_step_bluetooth self._abort_if_unique_id_configured() File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2394, in _abort_if_unique_id_configured self.hass.config_entries.async_schedule_reload(entry.entry_id) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1924, in async_schedule_reload self.hass.async_create_task( File "/usr/src/homeassistant/homeassistant/core.py", line 807, in async_create_task return self.async_create_task_internal(target, name, eager_start) File "/usr/src/homeassistant/homeassistant/core.py", line 829, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1962, in async_reload return await self.async_setup(entry_id, _lock=False) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1886, in async_setup await entry.async_setup(self.hass) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/casambi_bt/__init__.py", line 31, in async_setup_entry await api.connect() File "/config/custom_components/casambi_bt/__init__.py", line 102, in connect await self.casa.connect(device, self.password)
```
- [ ] Detected blocking call to read_bytes with args
```
Detected blocking call to read_bytes with args (PosixPath('/config/.storage/casambi_bt/6d2ab263d8b0/gQLL7hvDEDwJsw55c6RI25eQXEXzYeSx.json'),) inside the event loop by custom integration 'casambi_bt' at custom_components/casambi_bt/__init__.py, line 102: await self.casa.connect(device, self.password) (offender: /usr/local/lib/python3.12/site-packages/CasambiBt/_network.py, line 180: network = json.loads(cachedNetworkPah.read_bytes())), please report it to the author of the 'casambi_bt' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#read_bytes Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1962, in async_reload return await self.async_setup(entry_id, _lock=False) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1886, in async_setup await entry.async_setup(self.hass) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/casambi_bt/__init__.py", line 31, in async_setup_entry await api.connect() File "/config/custom_components/casambi_bt/__init__.py", line 102, in connect await self.casa.connect(device, self.password)
```
- [ ] Detected blocking call to open with args
```
Detected blocking call to open with args (PosixPath('/config/.storage/casambi_bt/6d2ab263d8b0/gQLL7hvDEDwJsw55c6RI25eQXEXzYeSx.json'),) inside the event loop by custom integration 'casambi_bt' at custom_components/casambi_bt/__init__.py, line 102: await self.casa.connect(device, self.password) (offender: /usr/local/lib/python3.12/pathlib.py, line 1019: with self.open(mode='rb') as f:), please report it to the author of the 'casambi_bt' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1962, in async_reload return await self.async_setup(entry_id, _lock=False) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1886, in async_setup await entry.async_setup(self.hass) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/casambi_bt/__init__.py", line 31, in async_setup_entry await api.connect() File "/config/custom_components/casambi_bt/__init__.py", line 102, in connect await self.casa.connect(device, self.password)
```
```
Detected blocking call to open with args (PosixPath('/config/.storage/casambi_bt/6d2ab263d8b0/types.pck'), 'wb') inside the event loop by custom integration 'casambi_bt' at custom_components/casambi_bt/__init__.py, line 102: await self.casa.connect(device, self.password) (offender: /usr/local/lib/python3.12/site-packages/CasambiBt/_network.py, line 87: pickle.dump(self._unitTypes, (cachePath / TYPES_CACHE_FILE).open("wb"))), please report it to the author of the 'casambi_bt' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1962, in async_reload return await self.async_setup(entry_id, _lock=False) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1886, in async_setup await entry.async_setup(self.hass) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/casambi_bt/__init__.py", line 31, in async_setup_entry await api.connect() File "/config/custom_components/casambi_bt/__init__.py", line 102, in connect await self.casa.connect(device, self.password)
```
- [ ] Detected blocking call to load_verify_locations with args
```
Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f2bd6bf50>,) inside the event loop by custom integration 'casambi_bt' at custom_components/casambi_bt/__init__.py, line 102: await self.casa.connect(device, self.password) (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 147: context.load_verify_locations(cafile=cafile)), please report it to the author of the 'casambi_bt' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1962, in async_reload return await self.async_setup(entry_id, _lock=False) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1886, in async_setup await entry.async_setup(self.hass) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/casambi_bt/__init__.py", line 31, in async_setup_entry await api.connect() File "/config/custom_components/casambi_bt/__init__.py", line 102, in connect await self.casa.connect(device, self.password)
```

**To Reproduce**
1. Update HA core to version 2024.9.0b2
2. Check the error logs

**Expected behavior**
No warnings.

**Screenshots**

**Versions**
- HA version: 2024.9.0b0
- Integration version: v0.1.2

**Logs**
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: August 31, 2024 at 22:26:11 (12 occurrences)
Last logged: August 31, 2024 at 22:27:26

**Comment by VincentVrijburg** [comment]
I have similar "detected blocking call" issues with my setup. It seems to limit the integration from adding the necessary entities to control my luminaires. The integration did add the network and the scenes I have in that network. This means I can control the scenes from HA, but not the luminaires individually yet.

I run HA version 2024.11.1 in a Docker container with latest integration version 0.1.3
My casambi network runs on the latest evolution firmware.

In addition, I get this line in the debug log:
`Version too new. Your network version is 11. Highest supported version is 10. Continue at your own risk.`

@tjorim I'm curious, what is your firmware type and network version?

**Comment by lkempf** [comment]
@VincentVrijburg This issue is just about best practices for integration authors and does not effect functionality. I haven't heard of you particular issue before so please open a new one.

**Comment by VincentVrijburg** [comment]
I created #93 for the new issue I had.

@lkempf This issue can be closed then, no? Since the `detected blocking call` issue is just a warning that does not impact functionality.

**Comment by tjorim** [comment]
It's still a warning that should be fixed because of potential performance issues. Pretty sure they will get to it when they have time and feel like it.

**Comment by lkempf** [comment]
> It's still a warning that should be fixed because of potential performance issues. Pretty sure they will get to it when they have time and feel like it.

It's already fixed in dev. I just haven't been able to get dev tested thoroughly.
