### ISSUE TITLE
Connection not working with ESP32 WROOM-32 esphome bluetooth proxy

### ISSUE THREAD

**Issue by Swissschoggi** [lkempf/casambi-bt-hass#96]
**Describe the bug**
I've been struggling with my occhio air lamps for some time now.
It kept randomly disconnecting and now i cant connect at all.
I'm using an ESP32 WROOM-32 with esphomes bluetooth proxy and have my casambi environment configured as described.
When i try to connect to the MAC with (what i assume is the password) i get the following in the logs:
`This error originated from a custom integration.

Logger: custom_components.casambi_bt.config_flow
Source: custom_components/casambi_bt/config_flow.py:148
integration: Casambi Bluetooth (documentation)
First occurred: 2:18:25 PM (11 occurrences)
Last logged: 2:39:19 PM

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/bleak_retry_connector/__init__.py", line 363, in establish_connection
    await client.connect(
    ...<3 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/habluetooth/wrappers.py", line 311, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/__init__.py", line 615, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 78, in _async_wrap_bluetooth_operation
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 329, in connect
    await connected_future
bleak.exc.BleakError: Error ESP_GATT_CONN_FAIL_ESTABLISH while connecting: Connection failed to establish

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/CasambiBt/_client.py", line 131, in connect
    self._gattClient = await establish_connection(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        BleakClient, device, "Casambi Network", self._on_disconnect
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/bleak_retry_connector/__init__.py", line 472, in establish_connection
    _raise_if_needed(name, device.address, exc)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak_retry_connector/__init__.py", line 336, in _raise_if_needed
    raise BleakAbortedError(f"{msg}: {ABORT_ADVICE}") from exc
bleak_retry_connector.BleakAbortedError: Casambi Network - ED:64:87:A7:21:C0: Failed to connect after 9 attempt(s): Error ESP_GATT_CONN_FAIL_ESTABLISH while connecting: Connection failed to establish: Interference/range; External Bluetooth adapter w/extension may help; Extension cables reduce USB 3 port interference

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/casambi_bt/config_flow.py", line 148, in async_step_user
    info = await _validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/casambi_bt/config_flow.py", line 60, in _validate_input
    await casa.connect(bt_device, data[CONF_PASSWORD])
  File "/usr/local/lib/python3.13/site-packages/CasambiBt/_casambi.py", line 154, in connect
    await self._connectClient()
  File "/usr/local/lib/python3.13/site-packages/CasambiBt/_casambi.py", line 159, in _connectClient
    await self._casaClient.connect()
  File "/usr/local/lib/python3.13/site-packages/CasambiBt/_client.py", line 140, in connect
    raise BluetoothError(e.args) from e
CasambiBt.errors.BluetoothError: ('Casambi Network - ED:64:87:A7:21:C0: Failed to connect after 9 attempt(s): Error ESP_GATT_CONN_FAIL_ESTABLISH while connecting: Connection failed to establish: Interference/range; External Bluetooth adapter w/extension may help; Extension cables reduce USB 3 port interference',)`

my ESP also gets the following logs which i cannot decipher lol:
`[14:46:39][D][esp32_ble_tracker:222]: Pausing scan to make connection...
[14:46:39][I][esp32_ble_client:066]: [0] [ED:64:87:A7:21:C0] 0x00 Attempting BLE connection
[14:46:39][D][esp-idf:000][BTU_TASK]: W (1944035) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e

[14:46:40][D][esp-idf:000][BTU_TASK]: W (1944143) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e

[14:46:40][D][esp-idf:000][BTU_TASK]: W (1944245) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e

[14:46:40][D][esp-idf:000][BTU_TASK]: W (1944352) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x3e

[14:46:40][D][esp-idf:000][BTU_TASK]: W (1944356) BT_APPL: gattc_conn_cb: if=4 st=0 id=4 rsn=0x3e

[14:46:40][D][esp-idf:000][BTU_TASK]: W (1944358) BT_APPL: gattc_conn_cb: if=5 st=0 id=5 rsn=0x3e

[14:46:40][D][esp-idf:000][BTU_TASK]: W (1944360) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e`

**To Reproduce**
Steps to reproduce the behavior:
1. have ESP32 WROOM-32
2. Go to Casambi_bt Intergration
3. fill out MAC and Password
4. See error

**Expected behavior**
I expected it to connect and prompt me to set up the areas of the lamps as it did before.

**Versions**
- HA version: 2024.12.5
- Integration version: cant check but i assume newest as i did an update recently

**Comment by Swissschoggi** [comment]
It somehow connected again but now the lights, after some time are unavailable again.
I found this log:
```

This error originated from a custom integration.

Logger: custom_components.casambi_bt
Source: custom_components/casambi_bt/__init__.py:188
integration: Casambi Bluetooth (documentation)
First occurred: 7:04:47 PM (1 occurrences)
Last logged: 7:04:47 PM

Error during reconnect. This is not unusual.
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 78, in _async_wrap_bluetooth_operation
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 555, in read_gatt_char
    return await self._client.bluetooth_gatt_read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._address_as_int, characteristic.handle, GATT_READ_TIMEOUT
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aioesphomeapi/client.py", line 788, in bluetooth_gatt_read
    return await self._bluetooth_gatt_read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aioesphomeapi/client.py", line 819, in _bluetooth_gatt_read
    resp = await self._send_bluetooth_message_await_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aioesphomeapi/client.py", line 486, in _send_bluetooth_message_await_response
    self._raise_for_ble_connection_change(address, resp, msg_types)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aioesphomeapi/client.py", line 722, in _raise_for_ble_connection_change
    raise BluetoothConnectionDroppedError(
    ...<3 lines>...
    )
aioesphomeapi.core.BluetoothConnectionDroppedError: Peripheral ED:64:87:A7:21:C0 changed connection status while waiting for BluetoothGATTReadResponse, BluetoothGATTErrorResponse: Insufficient authorization (8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/casambi_bt/__init__.py", line 102, in connect
    await self.casa.connect(device, self.password)
  File "/usr/local/lib/python3.13/site-packages/CasambiBt/_casambi.py", line 154, in connect
    await self._connectClient()
  File "/usr/local/lib/python3.13/site-packages/CasambiBt/_casambi.py", line 161, in _connectClient
    await self._casaClient.exchangeKey()
  File "/usr/local/lib/python3.13/site-packages/CasambiBt/_client.py", line 164, in exchangeKey
    firstResp = await self._gattClient.read_gatt_char(CASA_AUTH_CHAR_UUID)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/__init__.py", line 721, in read_gatt_char
    return await self._backend.read_gatt_char(char_specifier, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 88, in _async_wrap_bluetooth_operation
    raise BleakError(str(ex)) from ex
bleak.exc.BleakError: Peripheral ED:64:87:A7:21:C0 changed connection status while waiting for BluetoothGATTReadResponse, BluetoothGATTErrorResponse: Insufficient authorization (8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/casambi_bt/__init__.py", line 188, in _delayed_reconnect
    await self.try_reconnect()
  File "/config/custom_components/casambi_bt/__init__.py", line 210, in try_reconnect
    await self.connect()
  File "/config/custom_components/casambi_bt/__init__.py", line 115, in connect
    raise ConfigEntryError(
        f"Unexpected error creating network {self.address}"
    ) from err
homeassistant.exceptions.ConfigEntryError: Unexpected error creating network ED:64:87:A7:21:C0

```
